# Put this in your `Gemfile`.
# ```rb:Gemfile
# gem 'rubocop'
# gem 'rubocop-performance'
# gem 'rubocop-rails'
# ```

require:
  - rubocop-performance
  - rubocop-rails

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/**/*.rb
    - db/migrate/*.rb
    - lib/tasks/**/*.rake
    - Gemfile

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  Max: 120
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Style/AsciiComments:
  Enabled: false
